server:
  port: 8080
  servlet:
    context-path: /api
spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    name: springboot
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: lyl@654321
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000

logging:
  level:
    com.example.boot.mapper: debug
    com.example.boot.controller: info
    org.springframework: WARN
    org.spring.springboot.dao: debug

mybatis:
  mapper-locations: com/example/boot/mapper/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
